# Generated by Django 4.1.2 on 2022-11-24 11:01

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('profile_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[500, 500], upload_to=core.models.profile_img_path)),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=120, unique=True, verbose_name='Device Name')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('install_date', models.DateField(verbose_name='Install Date')),
                ('install_time', models.TimeField(verbose_name='Install Time')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Managed By')),
            ],
            options={
                'verbose_name': 'device',
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='TurbidityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='Record Date')),
                ('record_time', models.TimeField(auto_now_add=True, verbose_name='Record Time')),
                ('record_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1280, 720], upload_to=core.models.record_img_path)),
                ('valve_status', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=3, verbose_name='Vavle Status')),
                ('water_status', models.CharField(blank=True, choices=[('clean', 'clean'), ('dirty', 'dirty')], max_length=5, verbose_name='Water Status')),
                ('details', models.CharField(max_length=200, verbose_name='Details')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('record_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.device', verbose_name='Record Device')),
            ],
            options={
                'verbose_name': 'Turbidity Record',
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=120, unique=True, verbose_name='Component Name')),
                ('install_date', models.DateField(verbose_name='Install Date')),
                ('install_time', models.TimeField(verbose_name='Install Time')),
                ('installed_by', models.CharField(max_length=120, verbose_name='Installed By')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('device_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Device Link')),
            ],
            options={
                'verbose_name': 'component',
            },
        ),
    ]
