# Generated by Django 4.1.2 on 2022-10-24 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=120, unique=True, verbose_name='Device Name')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('install_date', models.DateField(verbose_name='Install Date')),
                ('device_status', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=7, verbose_name='Device Status')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Managed By')),
            ],
            options={
                'verbose_name': 'device',
            },
        ),
        migrations.CreateModel(
            name='TurbidityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='Record Date')),
                ('record_time', models.TimeField(auto_now_add=True, verbose_name='Record Time')),
                ('record_image', models.CharField(max_length=120, unique=True, verbose_name='Record Image')),
                ('valve_status', models.CharField(choices=[('on', 'on'), ('off', 'off')], max_length=3, verbose_name='Vavle Status')),
                ('water_status', models.CharField(choices=[('clean', 'clean'), ('dirty', 'dirty')], max_length=5, verbose_name='Water Status')),
                ('record_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Record Device')),
            ],
            options={
                'verbose_name': 'Turbidity Record',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=120, unique=True, verbose_name='Component Name')),
                ('install_date', models.DateField(verbose_name='Install Date')),
                ('installed_by', models.CharField(max_length=120, verbose_name='Installed By')),
                ('device_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Device Link')),
            ],
            options={
                'verbose_name': 'component',
            },
        ),
    ]
