# Generated by Django 4.1.2 on 2022-12-20 02:27

import core.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbidityrecord',
            name='record_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 300], upload_to=core.models.record_img_path),
        ),
    ]
