# Generated by Django 4.1.2 on 2022-10-31 10:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=core.models.default_profile_img_path, max_length=255, null=True, upload_to=core.models.profile_img_path),
        ),
    ]
