# Generated by Django 4.1.2 on 2022-12-20 02:42

import core.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_turbidityrecord_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbidityrecord',
            name='record_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[500, 500], upload_to=core.models.record_img_path),
        ),
    ]
