# Generated by Django 4.1.2 on 2022-10-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_turbidityrecord_record_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbidityrecord',
            name='record_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.device', verbose_name='Record Device'),
        ),
    ]
