# Generated by Django 4.1.2 on 2022-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_turbidityrecord_record_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbidityrecord',
            name='water_status',
            field=models.CharField(blank=True, choices=[('clean', 'clean'), ('dirty', 'dirty')], max_length=5, verbose_name='Water Status'),
        ),
    ]
