# Generated by Django 4.1.2 on 2023-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual', models.BooleanField()),
                ('clean', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='turbidityrecord',
            options={'ordering': ('created_on',), 'verbose_name': 'Turbidity Record'},
        ),
        migrations.AlterField(
            model_name='turbidityrecord',
            name='valve_status',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=3, verbose_name='Vavle Status'),
        ),
    ]
