# Generated by Django 4.1.2 on 2022-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_turbidityrecord_water_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbidityrecord',
            name='record_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='Record Image'),
        ),
    ]
