# Generated by Django 4.1.2 on 2023-01-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_clean_adminupdate_is_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminupdate',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
