# Generated by Django 4.1.2 on 2023-02-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminupdate_on_hold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUpdate',
        ),
    ]
